name: attention-encodings-v2
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.12
  - faiss-gpu=1.9.0
  - matplotlib
  - pytorch
  - pytorch-cuda=11.8
  - scikit-learn
  - transformers
  - gradio
